/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export class Esim extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * Get eSIM Status
     *
     * @remarks
     * Get status from eSIM
     */
    async getESIM(iccid: string, options?: RequestOptions): Promise<operations.GetESIMResponse> {
        const input$: operations.GetESIMRequest = {
            iccid: iccid,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = operations.GetESIMRequest$.outboundSchema.parse(input$);
        const body$ = null;

        const path$ = this.templateURLComponent("/esim")();

        const query$ = [
            enc$.encodeForm("iccid", payload$.iccid, { explode: true, charEncoding: "percent" }),
        ]
            .filter(Boolean)
            .join("&");

        let security$;
        if (typeof this.options$.oAuth2ClientCredentials === "function") {
            security$ = { oAuth2ClientCredentials: await this.options$.oAuth2ClientCredentials() };
        } else if (this.options$.oAuth2ClientCredentials) {
            security$ = { oAuth2ClientCredentials: this.options$.oAuth2ClientCredentials };
        } else {
            security$ = {};
        }
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.GetESIMResponse$.inboundSchema.parse({
                ...responseFields$,
                object: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, 400, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchResponse(response, 401, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMESIMResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Get eSIM Device
     *
     * @remarks
     * Get device info from an installed eSIM
     */
    async getESIMDevice(
        iccid: string,
        options?: RequestOptions
    ): Promise<operations.GetESIMDeviceResponse> {
        const input$: operations.GetESIMDeviceRequest = {
            iccid: iccid,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = operations.GetESIMDeviceRequest$.outboundSchema.parse(input$);
        const body$ = null;

        const pathParams$ = {
            iccid: enc$.encodeSimple("iccid", payload$.iccid, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path$ = this.templateURLComponent("/esim/{iccid}/device")(pathParams$);

        let security$;
        if (typeof this.options$.oAuth2ClientCredentials === "function") {
            security$ = { oAuth2ClientCredentials: await this.options$.oAuth2ClientCredentials() };
        } else if (this.options$.oAuth2ClientCredentials) {
            security$ = { oAuth2ClientCredentials: this.options$.oAuth2ClientCredentials };
        } else {
            security$ = {};
        }
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.GetESIMDeviceResponse$.inboundSchema.parse({
                ...responseFields$,
                object: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, 400, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMDeviceResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchResponse(response, 401, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMDeviceESIMResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Get eSIM History
     *
     * @remarks
     * Get history from an eSIM
     */
    async getESIMHistory(
        iccid: string,
        options?: RequestOptions
    ): Promise<operations.GetESIMHistoryResponse> {
        const input$: operations.GetESIMHistoryRequest = {
            iccid: iccid,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = operations.GetESIMHistoryRequest$.outboundSchema.parse(input$);
        const body$ = null;

        const pathParams$ = {
            iccid: enc$.encodeSimple("iccid", payload$.iccid, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path$ = this.templateURLComponent("/esim/{iccid}/history")(pathParams$);

        let security$;
        if (typeof this.options$.oAuth2ClientCredentials === "function") {
            security$ = { oAuth2ClientCredentials: await this.options$.oAuth2ClientCredentials() };
        } else if (this.options$.oAuth2ClientCredentials) {
            security$ = { oAuth2ClientCredentials: this.options$.oAuth2ClientCredentials };
        } else {
            security$ = {};
        }
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.GetESIMHistoryResponse$.inboundSchema.parse({
                ...responseFields$,
                object: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, 400, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMHistoryResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchResponse(response, 401, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMHistoryESIMResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Get eSIM MAC
     *
     * @remarks
     * Get MAC from eSIM
     */
    async getESIMMac(
        iccid: string,
        options?: RequestOptions
    ): Promise<operations.GetESIMMacResponse> {
        const input$: operations.GetESIMMacRequest = {
            iccid: iccid,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = operations.GetESIMMacRequest$.outboundSchema.parse(input$);
        const body$ = null;

        const pathParams$ = {
            iccid: enc$.encodeSimple("iccid", payload$.iccid, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path$ = this.templateURLComponent("/esim/{iccid}/mac")(pathParams$);

        let security$;
        if (typeof this.options$.oAuth2ClientCredentials === "function") {
            security$ = { oAuth2ClientCredentials: await this.options$.oAuth2ClientCredentials() };
        } else if (this.options$.oAuth2ClientCredentials) {
            security$ = { oAuth2ClientCredentials: this.options$.oAuth2ClientCredentials };
        } else {
            security$ = {};
        }
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.GetESIMMacResponse$.inboundSchema.parse({
                ...responseFields$,
                object: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, 400, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMMacResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchResponse(response, 401, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetESIMMacESIMResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }
}
