/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RFCDate } from "../../types";
import { z } from "zod";

export type TopUpESIMRequestBody = {
    /**
     * ID of the eSIM
     */
    iccid: string;
    /**
     * Size of the package in GB. The available options are 1, 2, 3, 5, 8, 20GB
     */
    dataLimitInGB: number;
    /**
     * Start date of the package's validity in the format 'yyyy-MM-dd'. This date can be set to the current day or any day within the next 12 months.
     */
    startDate: RFCDate;
    /**
     * End date of the package's validity in the format 'yyyy-MM-dd'. End date can be maximum 60 days after Start date.
     */
    endDate: RFCDate;
    /**
     * Email address where the purchase confirmation email will be sent (excluding QR Code & activation steps)
     */
    email?: string | undefined;
    /**
     * Epoch value representing the start time of the package's validity. This timestamp can be set to the current time or any time within the next 12 months.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    startTime?: number | undefined;
    /**
     * Epoch value representing the end time of the package's validity. End time can be maximum 60 days after Start time.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    endTime?: number | undefined;
};

export type TopUpESIMPurchase = {
    /**
     * ID of the purchase
     */
    id?: string | undefined;
    /**
     * ID of the package
     */
    packageId?: string | undefined;
    /**
     * Start date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ'
     */
    startDate?: Date | undefined;
    /**
     * End date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ'
     */
    endDate?: Date | undefined;
    /**
     * Creation date of the purchase in the format 'yyyy-MM-ddThh:mm:ssZZ'
     */
    createdDate?: Date | undefined;
    /**
     * Epoch value representing the start time of the package's validity
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    startTime?: number | undefined;
    /**
     * Epoch value representing the end time of the package's validity
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    endTime?: number | undefined;
};

export type TopUpESIMProfile = {
    /**
     * ID of the eSIM
     */
    iccid?: string | undefined;
};

/**
 * Successful Response
 */
export type TopUpESIMResponseBody = {
    purchase?: TopUpESIMPurchase | undefined;
    profile?: TopUpESIMProfile | undefined;
};

export type TopUpESIMResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful Response
     */
    object?: TopUpESIMResponseBody | undefined;
};

/** @internal */
export namespace TopUpESIMRequestBody$ {
    export type Inbound = {
        iccid: string;
        dataLimitInGB: number;
        startDate: string;
        endDate: string;
        email?: string | undefined;
        startTime?: number | undefined;
        endTime?: number | undefined;
    };

    export const inboundSchema: z.ZodType<TopUpESIMRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            iccid: z.string(),
            dataLimitInGB: z.number(),
            startDate: z.string().transform((v) => new RFCDate(v)),
            endDate: z.string().transform((v) => new RFCDate(v)),
            email: z.string().optional(),
            startTime: z.number().optional(),
            endTime: z.number().optional(),
        })
        .transform((v) => {
            return {
                iccid: v.iccid,
                dataLimitInGB: v.dataLimitInGB,
                startDate: v.startDate,
                endDate: v.endDate,
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.startTime === undefined ? null : { startTime: v.startTime }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
            };
        });

    export type Outbound = {
        iccid: string;
        dataLimitInGB: number;
        startDate: string;
        endDate: string;
        email?: string | undefined;
        startTime?: number | undefined;
        endTime?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TopUpESIMRequestBody> = z
        .object({
            iccid: z.string(),
            dataLimitInGB: z.number(),
            startDate: z.instanceof(RFCDate).transform((v) => v.toString()),
            endDate: z.instanceof(RFCDate).transform((v) => v.toString()),
            email: z.string().optional(),
            startTime: z.number().optional(),
            endTime: z.number().optional(),
        })
        .transform((v) => {
            return {
                iccid: v.iccid,
                dataLimitInGB: v.dataLimitInGB,
                startDate: v.startDate,
                endDate: v.endDate,
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.startTime === undefined ? null : { startTime: v.startTime }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
            };
        });
}

/** @internal */
export namespace TopUpESIMPurchase$ {
    export type Inbound = {
        id?: string | undefined;
        packageId?: string | undefined;
        startDate?: string | undefined;
        endDate?: string | undefined;
        createdDate?: string | undefined;
        startTime?: number | undefined;
        endTime?: number | undefined;
    };

    export const inboundSchema: z.ZodType<TopUpESIMPurchase, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string().optional(),
            packageId: z.string().optional(),
            startDate: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            endDate: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            createdDate: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            startTime: z.number().optional(),
            endTime: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.packageId === undefined ? null : { packageId: v.packageId }),
                ...(v.startDate === undefined ? null : { startDate: v.startDate }),
                ...(v.endDate === undefined ? null : { endDate: v.endDate }),
                ...(v.createdDate === undefined ? null : { createdDate: v.createdDate }),
                ...(v.startTime === undefined ? null : { startTime: v.startTime }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        packageId?: string | undefined;
        startDate?: string | undefined;
        endDate?: string | undefined;
        createdDate?: string | undefined;
        startTime?: number | undefined;
        endTime?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TopUpESIMPurchase> = z
        .object({
            id: z.string().optional(),
            packageId: z.string().optional(),
            startDate: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            endDate: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            createdDate: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            startTime: z.number().optional(),
            endTime: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.packageId === undefined ? null : { packageId: v.packageId }),
                ...(v.startDate === undefined ? null : { startDate: v.startDate }),
                ...(v.endDate === undefined ? null : { endDate: v.endDate }),
                ...(v.createdDate === undefined ? null : { createdDate: v.createdDate }),
                ...(v.startTime === undefined ? null : { startTime: v.startTime }),
                ...(v.endTime === undefined ? null : { endTime: v.endTime }),
            };
        });
}

/** @internal */
export namespace TopUpESIMProfile$ {
    export type Inbound = {
        iccid?: string | undefined;
    };

    export const inboundSchema: z.ZodType<TopUpESIMProfile, z.ZodTypeDef, Inbound> = z
        .object({
            iccid: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.iccid === undefined ? null : { iccid: v.iccid }),
            };
        });

    export type Outbound = {
        iccid?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TopUpESIMProfile> = z
        .object({
            iccid: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.iccid === undefined ? null : { iccid: v.iccid }),
            };
        });
}

/** @internal */
export namespace TopUpESIMResponseBody$ {
    export type Inbound = {
        purchase?: TopUpESIMPurchase$.Inbound | undefined;
        profile?: TopUpESIMProfile$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<TopUpESIMResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            purchase: z.lazy(() => TopUpESIMPurchase$.inboundSchema).optional(),
            profile: z.lazy(() => TopUpESIMProfile$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.purchase === undefined ? null : { purchase: v.purchase }),
                ...(v.profile === undefined ? null : { profile: v.profile }),
            };
        });

    export type Outbound = {
        purchase?: TopUpESIMPurchase$.Outbound | undefined;
        profile?: TopUpESIMProfile$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TopUpESIMResponseBody> = z
        .object({
            purchase: z.lazy(() => TopUpESIMPurchase$.outboundSchema).optional(),
            profile: z.lazy(() => TopUpESIMProfile$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.purchase === undefined ? null : { purchase: v.purchase }),
                ...(v.profile === undefined ? null : { profile: v.profile }),
            };
        });
}

/** @internal */
export namespace TopUpESIMResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: TopUpESIMResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<TopUpESIMResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => TopUpESIMResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: TopUpESIMResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TopUpESIMResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => TopUpESIMResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
